### ISSUE TITLE
VRC 700 some sensors only update with Home Assistant restart

### ISSUE THREAD

**Issue by stanislavpavlas** [signalkraft/mypyllant-component#103] opened 2024-02-14 08:31 UTC
### Problem description
Some sensors / especially those for hot water / don't refresh. 

### Log [1]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:533
Integration: Sensor (documentation, issues)
First occurred: 09:19:46 (1 occurrences)
Last logged: 09:19:46

Error adding entities for domain sensor with platform mypyllant
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 549, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/sensor.py", line 404, in native_value
    return self.zone.heating_state.display_value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'display_value'

### Log [2]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:352
Integration: Sensor (documentation, issues)
First occurred: 09:19:46 (1 occurrences)
Last logged: 09:19:46

Error while setting up mypyllant platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 549, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/sensor.py", line 404, in native_value
    return self.zone.heating_state.display_value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'display_value'

### Log [3]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/mypyllant/sensor.py:404
Integration: myVAILLANT (documentation, issues)
First occurred: 09:20:47 (5 occurrences)
Last logged: 09:24:52

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 412, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 183, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 492, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1047, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 995, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 549, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/sensor.py", line 404, in native_value
    return self.zone.heating_state.display_value
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'display_value'

**Comment by Rudi1967** [comment] 2024-02-14 14:01
Hi, 

I have the same issue: 

My system: heatingsystem: ecoTec Plus + VRC700 + sensonet

The following sensors do show the value at the time when the integration was installed or when HA ist startet. They are not refreshed 
1) Home Circuit 0 Current Flow Temperature
2) Home Domestic Hot Water 0 Tank Temperature

Other sensors, like the water pressure, are refreshed

**Comment by signalkraft** [comment] 2024-02-14 18:11
Could you please test with the latest pre-release? https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.3b6

**Comment by VaillantHassIo** [comment] 2024-02-14 18:13
@signalkraft  any chance you can pack this as HACS beta update? I just migrated to MyVaillant and guess i am using a VCR700 as well. thx

**Comment by VaillantHassIo** [comment] 2024-02-14 18:32
i got the following error during startup of the beta code

`2024-02-14 19:29:04.825 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: missing value for field "manual_mode_setpoint_cooling"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 72, in from_dict
    value = get_default_value_for_field(field, field_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/dataclasses.py", line 21, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 350, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 386, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 542, in from_api
    Zone.from_api(
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 386, in from_api
    ZoneCooling.from_api(**kwargs["cooling"]) if "cooling" in kwargs else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 313, in from_api
    return super().from_api(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 69, in from_api
    return from_dict(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 76, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "manual_mode_setpoint_cooling"
2024-02-14 19:29:04.843 DEBUG (MainThread) [custom_components.mypyllant] Refreshing DailyDataCoordinator
2024-02-14 19:29:04.844 DEBUG (MainThread) [custom_components.mypyllant] Starting async update data for DailyDataCoordinator
2024-02-14 19:29:04.844 DEBUG (MainThread) [custom_components.mypyllant] Waiting 118s until token refresh for michael_richter@gmx.de
2024-02-14 19:29:05.081 ERROR (MainThread) [custom_components.mypyllant] Unexpected error fetching myVAILLANT data: missing value for field "manual_mode_setpoint_cooling"
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 72, in from_dict
    value = get_default_value_for_field(field, field_type)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/dataclasses.py", line 21, in get_default_value_for_field
    raise DefaultValueNotFoundError()
dacite.dataclasses.DefaultValueNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 313, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/__init__.py", line 379, in _async_update_data
    async for system in await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 386, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 542, in from_api
    Zone.from_api(
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 386, in from_api
    ZoneCooling.from_api(**kwargs["cooling"]) if "cooling" in kwargs else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 313, in from_api
    return super().from_api(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 69, in from_api
    return from_dict(
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dacite/core.py", line 76, in from_dict
    raise MissingValueError(field.name)
dacite.exceptions.MissingValueError: missing value for field "manual_mode_setpoint_cooling"
2024-02-14 19:29:05.093 DEBUG (MainThread) [custom_components.mypyllant] Finished fetching myVAILLANT data in 0.249 seconds (success: False)
2024-02-14 19:29:05.098 WARNING (MainThread) [custom_components.mypyllant.binary_sensor] No system data, skipping binary sensors
2024-02-14 19:29:05.098 WARNING (MainThread) [custom_components.mypyllant.calendar] No system data, skipping calendar entities
2024-02-14 19:29:05.098 WARNING (MainThread) [custom_components.mypyllant.climate] No system data, skipping climate
2024-02-14 19:29:05.098 WARNING (MainThread) [custom_components.mypyllant.datetime] No system data, skipping date time entities
2024-02-14 19:29:05.098 WARNING (MainThread) [custom_components.mypyllant.number] No system data, skipping number entities
2024-02-14 19:29:05.099 WARNING (MainThread) [custom_components.mypyllant.sensor] No system data, skipping sensors
2024-02-14 19:29:05.099 DEBUG (MainThread) [custom_components.mypyllant.sensor] Daily data: None
2024-02-14 19:29:05.099 WARNING (MainThread) [custom_components.mypyllant.sensor] No daily data, skipping sensors
2024-02-14 19:29:05.099 WARNING (MainThread) [custom_components.mypyllant.switch] No system data, skipping switch entities
2024-02-14 19:29:05.099 WARNING (MainThread) [custom_components.mypyllant.water_heater] No system data, skipping water heater`

**Comment by signalkraft** [comment] 2024-02-14 18:36
@VaillantHassIo that's an unrelated issue, probably caused by [Govee](https://github.com/signalkraft/mypyllant-component/issues/54)

**Comment by VaillantHassIo** [comment] 2024-02-14 20:13
thx working great! so latest beta gives me 6 devices. unfortunately the old values for energy consumption are not taken into account. guess thats because they didnt migrate it to the new app

**Comment by stanislavpavlas** [comment] 2024-02-15 08:25
Hi, thanks for following up on that and would like to help testing it. How do I upload all files into custom_components folder? I am using File Editor within HA and that seems to only have option to upload one file.

**Comment by stanislavpavlas** [comment] 2024-02-16 09:17
thanks, for me now the update seems to be working / v0.7.3b6 /. The only two remaining errors seem to be with the start of HA.

**Log [1]**
This error originated from a custom integration.

Logger: custom_components.mypyllant.sensor
Source: custom_components/mypyllant/sensor.py:191
Integration: myVAILLANT (documentation, issues)
First occurred: 08:49:23 (1 occurrences)
Last logged: 08:49:23

No daily data, skipping sensors

**Log [2]**
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate (documentation, issues)
First occurred: 08:49:23 (1 occurrences)
Last logged: 08:49:23

Entity None (<class 'custom_components.mypyllant.climate.ZoneClimate'>) implements HVACMode(s): off, heat_cool, auto and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/signalkraft/mypyllant-component/issues

**Comment by Rudi1967** [comment] 2024-02-16 15:13
Thanks, I installed the latest version and now the sensors are refreshed. In addition I got now also the energy consumption which was not available before (for me). Problems I have still with the switch sensors. I got error when pushing away mode, boost or any other mode.

**Comment by signalkraft** [comment] 2024-02-16 20:23
@Rudi1967 could you try https://github.com/signalkraft/mypyllant-component/releases/tag/v0.7.3b7 please?

**Comment by Rudi1967** [comment] 2024-02-18 17:34
Thanks, I installed the mentioned version 7.3b7 and the situation is the following: 

sensos are available and refreshing but still issues with the operation modes:

**Away Mode:** When pushing this mode, the heating system switchesto away mode but after this, in HA no sensors are available. No possibility to switch back to automatic mode (eco) . Need to use the app of my mobile to switch back to automatic mode. Afterwards the sensors are again available.

**Sleeping mode:** When switching the sleeping mode, the heating system switches off. No possibility to re-activate the automatic mode from HA. Need to use the app of my mobile to re-activate it.

**Comment by signalkraft** [comment] 2024-02-23 20:16
The latest beta releases should fix those problems. I'll close this, since the original problem is fixed.

**Closed by signalkraft** 2024-02-23 20:16 UTC
