### ISSUE TITLE
Devices and Sensors Not Detected After Re-Adding Integration

### ISSUE THREAD

**Issue by andyx87** [signalkraft/mypyllant-component#229] opened 2024-10-30 20:13 UTC
### Before submitting a new issue

- [ X] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [X ] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [X ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Hello everyone,

Thanks for the recent update! Unfortunately, I'm still experiencing issues. While the hub is visible, none of my devices or sensors are being detected.

I removed and re-added the integration, but since then, nothing has shown up.

Has anyone else encountered this, or does anyone have suggestions for a fix?

Thank you for your help!

### Logs
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.mypyllant.coordinator
Quelle: helpers/update_coordinator.py:354
Integration: myVAILLANT (Dokumentation, Probleme)
Erstmals aufgetreten: 21:02:20 (8 Vorkommnisse)
Zuletzt protokolliert: 21:04:32

Unexpected error fetching myVAILLANT data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/coordinator.py", line 177, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 359, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 945, in from_api
    Circuit.from_api(system_id=system.id, timezone=system.timezone, **c)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 83, in from_api
    return cls(**data)
           ^^^^^^^^^^^
  File "pydantic/dataclasses.py", line 329, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
  File "pydantic/dataclasses.py", line 293, in pydantic.dataclasses._add_pydantic_validation_attributes.handle_extra_init
TypeError: Circuit.__init__() missing 1 required positional argument: 'circuit_state'

**Comment by thefrogbitesthefish** [comment] 2024-10-31 10:38
Same problem

**Comment by thefrogbitesthefish** [comment] 2024-10-31 13:56
Found this in a previous solution. No idea how to implement this, or if this can be part of the integration itself...

dataclass(config=MyPyllantConfig) class Circuit(MyPyllantDataClass): system_id: str index: int circuit_state: CircuitState | None = None mixer_circuit_type_external: str | None = None set_back_mode_enabled: bool | None = None zones: list = field(default_factory=list) is_cooling_allowed: bool | None = None current_circuit_flow_temperature: float | None = None heating_curve: float | None = None heating_flow_temperature_minimum_setpoint: float | None = None heating_flow_temperature_maximum_setpoint: float | None = None min_flow_temperature_setpoint: float | None = None calculated_energy_manager_state: str | None = None

**Comment by signalkraft** [comment] 2024-10-31 23:25
Duplicate of #230

**Closed by signalkraft** 2024-10-31 23:25 UTC
