### ISSUE TITLE
Quick veto slider produce an error

### ISSUE THREAD

**Issue by Gio-dot** [signalkraft/mypyllant-component#73] opened 2024-01-04 18:29 UTC
### Before submitting a new issue

- [x] I'm not using the older Vaillant sensoAPP (which is unsupported by this integration)
- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [ ] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description

Moving the new slider quick veto time, an error occours:

![image](https://github.com/signalkraft/mypyllant-component/assets/55327160/2160eb6d-9e5a-4a8c-b5c6-ddc738b7e47c)

![2024-01-04 19_23_39-](https://github.com/signalkraft/mypyllant-component/assets/55327160/20514a38-461c-4992-a428-07405824ca64)

### Logs

```
Put your debug logs here
Be careful not to include tokens, emails, and other personal information
```

**Comment by Gio-dot** [comment] 2024-02-10 19:46
Same issue with the Latest version update

**Comment by signalkraft** [comment] 2024-02-23 20:19
The intended behavior of the slider is that it becomes unavailable when quick veto is off (since you need to set a veto temperature for the feature to make sense, and the slider only provides duration). If quick veto is on, it should work without errors.

Are you still getting errors, or is it simply unavailable?

**Comment by Gio-dot** [comment] 2024-02-23 23:48
> The intended behavior of the slider is that it becomes unavailable when quick veto is off (since you need to set a veto temperature for the feature to make sense, and the slider only provides duration). If quick veto is on, it should work without errors.
> 
> Are you still getting errors, or is it simply unavailable?

Ok, i know how Quick veto work. Still a long list of "commands" appear when i move veto slider. After some seconds that list disappear and the new slider position seem to be ok
![Screenshot_20240224_004129_Home Assistant](https://github.com/signalkraft/mypyllant-component/assets/55327160/43c812f2-c644-4fc1-98df-4238d4292360)

**Comment by signalkraft** [comment] 2024-02-24 11:10
Can you post logs from system > logs? The messages in your screenshot are cut off before the interesting part.

**Comment by signalkraft** [comment] 2024-03-24 17:17
If you can still reproduce the problem, and post debug logs let me know. I'll close this for now.

**Closed by signalkraft** 2024-03-24 17:17 UTC

**Comment by gio-dot** [comment] 2024-03-30 10:09
Hi, since the last update quick veto slider is no longer available
![Screenshot_20240330_110627_Home Assistant](https://github.com/signalkraft/mypyllant-component/assets/55327160/ab4cf18d-f888-46f8-886a-b2ef4bf591a2)
