### ISSUE TITLE
No System Data available. Whole integration stopped working. 

### ISSUE THREAD

**Issue by Krzysztonek** [signalkraft/mypyllant-component#216] opened 2024-09-25 20:09 UTC
### Before submitting a new issue

- [x] I [redownloaded the latest release](https://my.home-assistant.io/redirect/hacs_repository/?owner=signalkraft&repository=mypyllant-component) and restarted Home Assistant
- [x] I've checked [known issues](https://signalkraft.com/mypyllant-component/#known-issues)
- [x] I've [enabled debug logs](https://signalkraft.com/mypyllant-component/3-contributing/#debugging) and attached the relevant logs to this ticket

### Problem description
![obraz](https://github.com/user-attachments/assets/edce4813-f2c6-4ec7-a2aa-3c1d3b1a41d1)

Since over 2 days this integration doesn't work for me.
I'm constantly getting this:
![obraz](https://github.com/user-attachments/assets/62d29476-3ab8-487c-91a0-1acad7a07d85)

Actually all the sensors of myVAILLANT integration are being skipped (remain `unavailable`).
What can I do to fix it? Please, advise.

### Logs

```
2024-10-04 10:32:55.909 DEBUG (MainThread) [custom_components.mypyllant] Refreshing SystemCoordinator
2024-10-04 10:32:55.909 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Starting async update data for SystemCoordinator
2024-10-04 10:32:55.910 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Waiting 119s until token refresh
2024-10-04 10:32:55.924 DEBUG (MainThread) [myPyllant.http_client] Starting GET to https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/homes
2024-10-04 10:32:56.140 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Quota was hit 0s ago on 2024-10-04 08:32:56.140637+00:00
Traceback (most recent call last):
  File "/config/custom_components/mypyllant/coordinator.py", line 177, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 337, in get_systems
    async for home in homes:
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 294, in get_homes
    async with self.aiohttp_session.get(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1355, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 787, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/http_client.py", line 73, in on_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Quota Exceeded', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/homes'
2024-10-04 10:32:56.168 ERROR (MainThread) [custom_components.mypyllant.coordinator] Error fetching myVAILLANT data: Quota Exceeded on https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/homes, skipping update of myVAILLANT data for another 10800s
2024-10-04 10:32:56.168 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Finished fetching myVAILLANT data in 0.259 seconds (success: False)
2024-10-04 10:32:56.169 DEBUG (MainThread) [custom_components.mypyllant] Refreshing DailyDataCoordinator
2024-10-04 10:32:56.169 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Quota was hit 0s ago on 2024-10-04 08:32:56.140637+00:00
Traceback (most recent call last):
  File "/config/custom_components/mypyllant/coordinator.py", line 177, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 337, in get_systems
    async for home in homes:
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 294, in get_homes
    async with self.aiohttp_session.get(
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 1355, in __aenter__
    self._resp: _RetType = await self._coro
                           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 787, in _request
    await raise_for_status(resp)
  File "/usr/local/lib/python3.12/site-packages/myPyllant/http_client.py", line 73, in on_raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Quota Exceeded', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/homes'
2024-10-04 10:32:56.197 ERROR (MainThread) [custom_components.mypyllant.coordinator] Error fetching myVAILLANT data: Quota Exceeded on https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/homes, skipping update of myVAILLANT data for another 10800s
2024-10-04 10:32:56.197 DEBUG (MainThread) [custom_components.mypyllant.coordinator] Finished fetching myVAILLANT data in 0.028 seconds (success: False)

```
When checking the url `url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/homes'` from the log above I'm getting this:
```
{ "statusCode": 401, "message": "Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API." }
```

**Comment by jstott1070** [comment] 2024-10-09 08:25
I also have just seen the same issue - only just set the integration up yesterday with it all working great, however overnight all sensors have switched to Unavailable. I have restarted the integration, rebooted HA and my router with no luck. The MyVailliant app is still connecting and receiving updates, so not sure why this integration has stopped working.

**Comment by hkcrainer** [comment] 2024-10-09 10:18
Same Probleme here

**Comment by frans0180** [comment] 2024-10-09 10:18
Same Probleme here

**Comment by BlueDin1986** [comment] 2024-10-09 11:23
I have the same Problem. Log:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/coordinator.py", line 177, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 358, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 944, in from_api
    Zone.from_api(
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 430, in from_api
    data["cooling"] = ZoneCooling.from_api(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 326, in from_api
    **data["time_program_cooling"]
      ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'time_program_cooling'
![Screenshot 2024-10-09 132227](https://github.com/user-attachments/assets/88d0ae38-2af8-45d9-b8e6-ca58a5d5d843)

**Comment by alexanderbraun3** [comment] 2024-10-09 11:37
same Problem here. Whole integration stopped working.

"Access denied due to missing subscription key. Make sure to include subscription key when making requests to an API."

**Comment by DanielStockinger** [comment] 2024-10-09 13:15
same Problem here

**Comment by mastersteve1** [comment] 2024-10-09 13:26
me too ;-)

**Comment by btxluke** [comment] 2024-10-09 16:19
Seems pretty universal. Me too.

**Comment by CaptainHam** [comment] 2024-10-09 16:24
Same here…occurred earlier today randomly. I’ve made no updates of any kind to suddenly make it stop working

**Comment by tstraetgen** [comment] 2024-10-09 18:29
Same problem here!

**Comment by lanthi63** [comment] 2024-10-09 20:12
same pb here since this morning 8:17

**Comment by git-jhs** [comment] 2024-10-09 20:37
Same here 🫤

**Comment by signalkraft** [comment] 2024-10-09 21:13
https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.15

This may fix it, if not someone needs to post [test data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) since I don't have the same problem with my setup.

**Comment by btxluke** [comment] 2024-10-09 21:24
> https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.15
> 
> This may fix it, if not someone needs to post [test data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) since I don't have the same problem with my setup.

No good for me.

```
{% set action_response = {"homes":[{"homeName":"0d0b3100662269abeb8d2d7a37ffb27b4921ca77","serialNumber":"b32259a79c4ff1c0ea2de15e2ffe3e2e055e0f1e","systemId":"f773cad88b6c600acb2ea77cac182707c6168638","productMetadata":{"productType":"VR921","productionYear":"23","productionWeek":"34","articleNumber":"0020260963"},"state":"CLAIMED","migrationState":"FINISHED","migrationFinishedAt":"2023-12-11T15:40:20.076678811Z","onlineState":"ONLINE","firmware":{"version":"0357.40.35","connectedToOldIoTPlatform":null,"updateEnabled":true,"updateRequired":false},"nomenclature":"VR 921","cag":false,"countryCode":"GB","productInformation":"VR921","firmwareVersion":"0357.40.35"}],"f773cad88b6c600acb2ea77cac182707c6168638":{"control_identifier":{"controlIdentifier":"tli"},"time_zone":{"timeZone":"Europe/London"},"diagnostic_trouble_codes":[{"serialNumber":"ab68ee91797a0eaf675650d967008e8a180dbdb6","articleNumber":"0020262148","codes":[]},{"serialNumber":"3765b64fc91ddca1e6e2fd953a67ea016dc72511","articleNumber":"0010047381","codes":[]},{"serialNumber":"b32259a79c4ff1c0ea2de15e2ffe3e2e055e0f1e","articleNumber":"0020260963","codes":[]},{"serialNumber":"0425058b59bf758a83fe2f2fec8f81a769ec74cb","articleNumber":"0010031644","codes":[]}],"connection_status":{"connected":true},"system":{"state":{"system":{"outdoorTemperature":7.5664062,"outdoorTemperatureAverage24h":10.386719,"energyManagerState":"STANDBY","systemOff":false},"zones":[{"index":0,"desiredRoomTemperatureSetpointHeating":16.5,"desiredRoomTemperatureSetpoint":16.5,"currentRoomTemperature":20.1875,"currentRoomHumidity":64,"currentSpecialFunction":"NONE","heatingState":"IDLE","quickVetoStartDateTime":"1970-01-01T00:00:00Z","quickVetoEndDateTime":"1970-01-01T00:00:00Z"}],"circuits":[{"index":0,"circuitState":"STANDBY","currentCircuitFlowTemperature":22,"heatingCircuitFlowSetpoint":0,"calculatedEnergyManagerState":"HEATING_STANDBY"}],"dhw":[{"index":255,"currentSpecialFunction":"REGULAR","currentDhwTemperature":44}],"ventilation":[]},"properties":{"system":{"controllerType":"VRC720","isLegionallaProtectionActivated":"MONDAY","systemScheme":10,"backupHeaterType":"CONDENSING","backupHeaterAllowedFor":"DISABLED","temporaryAllowBackupHeater":"DISABLED","moduleConfigurationVR71":3,"energyProvidePowerCutBehavior":"DISABLE_COOLING","smartPhotovoltaicBufferOffset":10,"externalEnergyManagementActivation":false},"zones":[{"index":0,"isActive":true,"zoneBinding":"CENTRAL_CONTROL","isCoolingAllowed":false,"associatedCircuitIndex":0}],"circuits":[{"index":0,"mixerCircuitTypeExternal":"HEATING","heatingCircuitType":"DIRECT_HEATING_CIRCUIT"}],"dhw":[{"index":255,"minSetpoint":35,"maxSetpoint":70}],"ventilation":[]},"configuration":{"system":{"continuousHeatingStartSetpoint":-26,"alternativePoint":-21,"heatingCircuitBivalencePoint":-20,"dhwBivalencePoint":-20,"adaptiveHeatingCurve":false,"dhwMaximumLoadingTime":60,"dhwHysteresis":5,"dhwFlowSetpointOffset":15,"continuousHeatingRoomSetpoint":20,"manualCoolingStartDate":"2019-01-01T00:00:00Z","manualCoolingEndDate":"2019-01-01T00:00:00Z","hybridControlStrategy":"BIVALENCE_POINT","maxFlowSetpointHpError":25,"dhwMaximumTemperature":80,"maximumPreheatingTime":0},"zones":[{"index":0,"general":{"name":"Zone 1","holidayStartDateTime":"2015-01-01T00:00:00Z","holidayEndDateTime":"2015-01-01T00:00:00Z","holidaySetpoint":15},"heating":{"operationModeHeating":"TIME_CONTROLLED","setBackTemperature":16.5,"manualModeSetpointHeating":19.5,"timeProgramHeating":{"metaInfo":{"minSlotsPerDay":0,"maxSlotsPerDay":12,"setpointRequiredPerSlot":true},"monday":[{"startTime":450,"endTime":1140,"setpoint":19},{"startTime":1140,"endTime":1320,"setpoint":19}],"tuesday":[{"startTime":450,"endTime":1140,"setpoint":19},{"startTime":1140,"endTime":1320,"setpoint":19}],"wednesday":[{"startTime":450,"endTime":1140,"setpoint":19},{"startTime":1140,"endTime":1320,"setpoint":19}],"thursday":[{"startTime":450,"endTime":1140,"setpoint":19},{"startTime":1140,"endTime":1320,"setpoint":19}],"friday":[{"startTime":450,"endTime":1140,"setpoint":19},{"startTime":1140,"endTime":1320,"setpoint":19}],"saturday":[{"startTime":450,"endTime":1140,"setpoint":19},{"startTime":1140,"endTime":1320,"setpoint":19}],"sunday":[{"startTime":450,"endTime":1140,"setpoint":19},{"startTime":1140,"endTime":1320,"setpoint":19}]}},"cooling":{}}],"circuits":[{"index":0,"heatingCurve":1,"heatingFlowTemperatureMinimumSetpoint":15,"heatingFlowTemperatureMaximumSetpoint":47,"heatDemandLimitedByOutsideTemperature":30,"heatingCircuitFlowSetpointExcessOffset":0,"setBackModeEnabled":true,"roomTemperatureControlMode":"THERMOSTAT_FUNCTION","epsilon":2}],"dhw":[{"index":255,"operationModeDhw":"TIME_CONTROLLED","tappingSetpoint":45,"holidayStartDateTime":"2015-01-01T00:00:00Z","holidayEndDateTime":"2015-01-01T00:00:00Z","timeProgramDhw":{"metaInfo":{"minSlotsPerDay":0,"maxSlotsPerDay":3,"setpointRequiredPerSlot":false},"monday":[{"startTime":370,"endTime":1320}],"tuesday":[{"startTime":370,"endTime":1320}],"wednesday":[{"startTime":370,"endTime":1320}],"thursday":[{"startTime":370,"endTime":1320}],"friday":[{"startTime":370,"endTime":1320}],"saturday":[{"startTime":370,"endTime":1320}],"sunday":[{"startTime":370,"endTime":1320}]},"timeProgramCirculationPump":{"metaInfo":{"minSlotsPerDay":0,"maxSlotsPerDay":3,"setpointRequiredPerSlot":false},"monday":[{"startTime":360,"endTime":1320}],"tuesday":[{"startTime":360,"endTime":1320}],"wednesday":[{"startTime":360,"endTime":1320}],"thursday":[{"startTime":360,"endTime":1320}],"friday":[{"startTime":360,"endTime":1320}],"saturday":[{"startTime":450,"endTime":1410}],"sunday":[{"startTime":450,"endTime":1320}]}}],"ventilation":[]}},"current_system":{"system_type":"HEATPUMP","has_emf_capable_devices":true,"primary_heat_generator":{"device_uuid":"c05c70a5629b9cdaeb79e49fe09c306ab3a2a172","ebus_id":"HMU03","spn":351,"bus_coupler_address":0,"article_number":"0010047381","emfValid":true,"device_serial_number":"3765b64fc91ddca1e6e2fd953a67ea016dc72511","device_type":"HEATPUMP","first_data":"2023-11-10T16:21:46Z","last_data":"2024-10-09T20:53:08.205Z","data":[{"operation_mode":"DOMESTIC_HOT_WATER","value_type":"CONSUMED_ELECTRICAL_ENERGY","calculated":false,"from":"2023-11-10T16:21:46Z","to":"2024-10-09T20:53:07.314Z"},{"operation_mode":"HEATING","value_type":"CONSUMED_ELECTRICAL_ENERGY","calculated":false,"from":"2023-11-10T16:21:46Z","to":"2024-10-09T20:53:07.08Z"},{"operation_mode":"DOMESTIC_HOT_WATER","value_type":"EARNED_ENVIRONMENT_ENERGY","calculated":false,"from":"2023-11-10T16:21:46Z","to":"2024-10-09T20:53:08.001Z"},{"operation_mode":"HEATING","value_type":"EARNED_ENVIRONMENT_ENERGY","calculated":false,"from":"2023-11-10T16:21:46Z","to":"2024-10-09T20:53:07.751Z"},{"operation_mode":"HEATING","value_type":"HEAT_GENERATED","calculated":true,"from":"2023-11-10T16:21:46Z","to":"2024-10-09T20:53:07.08Z"},{"operation_mode":"DOMESTIC_HOT_WATER","value_type":"HEAT_GENERATED","calculated":true,"from":"2023-11-10T16:21:46Z","to":"2024-10-09T20:53:07.314Z"}],"product_name":"aroTHERM plus"},"secondary_heat_generators":[],"electric_backup_heater":null,"solar_station":null,"ventilation":null,"gateway":null},"mpc":{"devices":[]},"rts":{"statistics":[]},"device_buckets":{"startDate":"2024-10-08T00:00:00Z","endDate":"2024-10-09T00:00:00Z","resolution":"HOUR","operationMode":"DOMESTIC_HOT_WATER","energyType":"CONSUMED_ELECTRICAL_ENERGY","totalConsumption":999.7183098591549,"data":[{"startDate":"2024-10-08T00:00:00Z","endDate":"2024-10-08T01:00:00Z","value":0},{"startDate":"2024-10-08T01:00:00Z","endDate":"2024-10-08T02:00:00Z","value":0},{"startDate":"2024-10-08T02:00:00Z","endDate":"2024-10-08T03:00:00Z","value":0},{"startDate":"2024-10-08T03:00:00Z","endDate":"2024-10-08T04:00:00Z","value":0},{"startDate":"2024-10-08T04:00:00Z","endDate":"2024-10-08T05:00:00Z","value":0},{"startDate":"2024-10-08T05:00:00Z","endDate":"2024-10-08T06:00:00Z","value":0},{"startDate":"2024-10-08T06:00:00Z","endDate":"2024-10-08T07:00:00Z","value":0},{"startDate":"2024-10-08T07:00:00Z","endDate":"2024-10-08T08:00:00Z","value":0},{"startDate":"2024-10-08T08:00:00Z","endDate":"2024-10-08T09:00:00Z","value":0},{"startDate":"2024-10-08T09:00:00Z","endDate":"2024-10-08T10:00:00Z","value":0},{"startDate":"2024-10-08T10:00:00Z","endDate":"2024-10-08T11:00:00Z","value":0},{"startDate":"2024-10-08T11:00:00Z","endDate":"2024-10-08T12:00:00Z","value":0},{"startDate":"2024-10-08T12:00:00Z","endDate":"2024-10-08T13:00:00Z","value":0},{"startDate":"2024-10-08T13:00:00Z","endDate":"2024-10-08T14:00:00Z","value":679.7183098591549},{"startDate":"2024-10-08T14:00:00Z","endDate":"2024-10-08T15:00:00Z","value":320},{"startDate":"2024-10-08T15:00:00Z","endDate":"2024-10-08T16:00:00Z","value":0},{"startDate":"2024-10-08T16:00:00Z","endDate":"2024-10-08T17:00:00Z","value":0},{"startDate":"2024-10-08T17:00:00Z","endDate":"2024-10-08T18:00:00Z","value":0},{"startDate":"2024-10-08T18:00:00Z","endDate":"2024-10-08T19:00:00Z","value":0},{"startDate":"2024-10-08T19:00:00Z","endDate":"2024-10-08T20:00:00Z","value":0},{"startDate":"2024-10-08T20:00:00Z","endDate":"2024-10-08T21:00:00Z","value":0},{"startDate":"2024-10-08T21:00:00Z","endDate":"2024-10-08T22:00:00Z","value":0},{"startDate":"2024-10-08T22:00:00Z","endDate":"2024-10-08T23:00:00Z","value":0},{"startDate":"2024-10-08T23:00:00Z","endDate":"2024-10-09T00:00:00Z","value":0}]},"rbr":{"rbrCapable":true},"rooms":[],"energy_management":{"energyManager":{"available":false,"compatible":false},"energyManagementStatus":{"thermalStorage":{"domesticHotWater":{"available":false,"selected":false},"heatingBufferCylinder":{"available":false,"selected":true}}}},"ship_self":{"ski":"5b89e12c6ad57775e302e1ae55ad9fa625255470","brand":"Vaillant","type":"Gateway","model":"VR921","spineEnabled":false,"spineEnabledStatus":"DETERMINED","spineCapable":true}}} %}
```

**Comment by CaptainHam** [comment] 2024-10-09 21:25
Unfortunately 0.8.16 does not resolve the issue with ZoneCooling for me.


This error originated from a custom integration.

Logger: custom_components.mypyllant.coordinator
Source: helpers/update_coordinator.py:354
integration: myVAILLANT (documentation, issues)
First occurred: 22:20:43 (2 occurrences)
Last logged: 22:20:43

Unexpected error fetching myVAILLANT data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/mypyllant/coordinator.py", line 177, in _async_update_data
    data = [
           ^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/api.py", line 358, in get_systems
    system = System.from_api(
             ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 945, in from_api
    Zone.from_api(
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 441, in from_api
    return super().from_api(**data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/myPyllant/models.py", line 83, in from_api
    return cls(**data)
           ^^^^^^^^^^^
  File "pydantic/dataclasses.py", line 332, in pydantic.dataclasses._add_pydantic_validation_attributes.new_init
  File "pydantic/dataclasses.py", line 447, in pydantic.dataclasses._dataclass_validate_values
pydantic.error_wrappers.ValidationError: 1 validation error for Zone
cooling
  ZoneCooling.__init__() missing 4 required positional arguments: 'control_identifier', 'setpoint_cooling', 'operation_mode_cooling', and 'time_program_cooling' (type=type_error)

**Comment by Krzysztonek** [comment] 2024-10-09 21:27
> his may fix it, if not someone needs to post [test data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) since I don't have the same problem with my setup.

[Here](https://github.com/signalkraft/mypyllant-component/issues/218#issue-2574301141) you can find the result of `TEST DATA` action.

**Comment by iamgeert** [comment] 2024-10-09 21:33
> https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.15
> 
> This may fix it, if not someone needs to post [test data](https://signalkraft.com/mypyllant-component/3-contributing/#contributing-test-data) since I don't have the same problem with my setup.

[testdata.txt](https://github.com/user-attachments/files/17318939/testdata.txt)

**Comment by signalkraft** [comment] 2024-10-09 21:37
https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.17 should work, thanks for the test data.

**Comment by iamgeert** [comment] 2024-10-09 21:38
> https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.17 should work, thanks for the test data.

Thanks; it works 👍🏻

**Comment by BuhJuhWuh** [comment] 2024-10-09 21:41
0.8.17 is working for me. Thanks for the quick update.

**Comment by philsson** [comment] 2024-10-09 22:18
Same problem here. Installed through HACS and does not offer any updates currently. Im on v0.8.14. Anyone know if I can force HACS to give me the latest version?

**Comment by frans0180** [comment] 2024-10-10 02:42
👍👍👍

**Comment by alexanderbraun3** [comment] 2024-10-10 04:43
Thank you very much for quick fixing 👍🏼

**Comment by DanielStockinger** [comment] 2024-10-10 04:46
@signalkraft 
Many Thanks for quick fixing. 👍👍👍👍

**Comment by Krzysztonek** [comment] 2024-10-10 07:15
Indeed, this 8.17 version worked fine for me yesterday evening (Poland) for a while. I was so happy.
However, today's morning this issue occurred again.
Please see my full log file (sanitized):
[home-assistant_mypyllant_2024-10-10T06-44-49.989Z.log](https://github.com/user-attachments/files/17323859/home-assistant_mypyllant_2024-10-10T06-44-49.989Z.log)

**Comment by btxluke** [comment] 2024-10-10 12:24
@signalkraft thanks - that's sorted it for me.

**Comment by iamgeert** [comment] 2024-10-11 20:39
> Indeed, this 8.17 version worked fine for me yesterday evening (Poland) for a while. I was so happy. However, today's morning this issue occurred again. Please see my full log file (sanitized): [home-assistant_mypyllant_2024-10-10T06-44-49.989Z.log](https://github.com/user-attachments/files/17323859/home-assistant_mypyllant_2024-10-10T06-44-49.989Z.log)

aiohttp.client_exceptions.ClientResponseError: 403, message='**Quota Exceeded**', url='https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/homes'
2024-10-10 08:38:37.348 ERROR (MainThread) [custom_components.mypyllant.coordinator] **Error fetching myVAILLANT data: Quota Exceeded** on https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/homes, **skipping update of myVAILLANT data for another 10800s**

That's a 3hours no updates,...
Try to adjust your configuration: Seconds between updates, Seconds between energy data updates

**Comment by Krzysztonek** [comment] 2024-10-11 22:00
> Try to adjust your configuration: Seconds between updates, Seconds between energy data updates

These are my settings:

![obraz](https://github.com/user-attachments/assets/2afb2aa4-77d4-450e-925c-3fb34854d20a)
![obraz](https://github.com/user-attachments/assets/4be0812f-2f4f-46a3-b4c7-4994b0a10c32)

I haven't changed anything here since months and this integration worked fine for me so far.. 
Looks this is not an issue with settings but with API..

**Comment by Richardstables** [comment] 2024-10-17 10:57
I have also now started getting this same error.

Error fetching myVAILLANT data: Quota Exceeded on https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/0aba2718-dd8c-4ee4-bf11-8a9ab5806023/devices/8c2d0644-e517-583a-979f-0b421df4fe17/buckets?resolution=HOUR&operationMode=HEATING&energyType=HEAT_GENERATED&startDate=2024-10-17T00:00:00.000%2B01:00&endDate=2024-10-18T00:00:00.000%2B01:00, skipping update of myVAILLANT data for another 10800s
Error fetching myVAILLANT data: Quota Exceeded on https://api.vaillant-group.com/service-connected-control/end-user-app-api/v1/emf/v2/0aba2718-dd8c-4ee4-bf11-8a9ab5806023/devices/8c2d0644-e517-583a-979f-0b421df4fe17/buckets?resolution=HOUR&operationMode=HEATING&energyType=HEAT_GENERATED&startDate=2024-10-17T00:00:00.000%2B01:00&endDate=2024-10-18T00:00:00.000%2B01:00, skipping update of myVAILLANT data for another 10740s

**Comment by Flori1007** [comment] 2024-10-18 05:29
> I have managed to get mine working again. I had to delete the hub connection and re-add it. Once I had done this and ticked the relevant boxes in the configuration to fetch real time data and then reloaded the integration it all started to work again.

and then you have to make all automations and stuff from new? all entitites will be gone right?

**Comment by signalkraft** [comment] 2024-11-01 17:34
Duplicate of https://github.com/signalkraft/mypyllant-component/issues/226 - I'm closing this one

**Closed by signalkraft** 2024-11-01 17:34 UTC
