### ISSUE TITLE
Issue after upgrade home assistant to  2024.6.0

### ISSUE THREAD

**Issue by Terikos** [signalkraft/mypyllant-component#168] opened 2024-06-05 20:35 UTC
### Problem description
After upgrade to 2024.6.0 inter gratin is not loading.

### Logs
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 10:24:20 PM (3 occurrences)
Last logged: 10:24:40 PM

Unable to install package myPyllant==0.8.11: ERROR: Cannot install mypyllant==0.8.11 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by electricfire** [comment] 2024-06-05 21:39
Want to echo the same after upgrading HA to the version mentioned above
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 9:58:28 PM (3 occurrences)
Last logged: 9:58:33 PM

Unable to install package myPyllant==0.8.9: ERROR: Cannot install mypyllant==0.8.9 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by willenic** [comment] 2024-06-05 21:47
I also have the same error when updating HA core and supervisor

**Comment by Krzysztonek** [comment] 2024-06-05 21:54
exactly the same error here after updating HA (both core and supervisor) to 2024.6:

`Unable to install package myPyllant==0.8.9: ERROR: Cannot install mypyllant==0.8.9 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
`

**Comment by gio-dot** [comment] 2024-06-06 03:00
+1 here

**Comment by irozakos** [comment] 2024-06-06 05:08
Same errors here too.

**Comment by PV-Joe** [comment] 2024-06-06 05:13
Same issue here.
Hoping for a solution.

**Comment by chris8484** [comment] 2024-06-06 05:24
The same error here too.

**Comment by lecocqe** [comment] 2024-06-06 05:28
+1

**Comment by R1200G** [comment] 2024-06-06 06:38
Same problem..

**Comment by wardog-82** [comment] 2024-06-06 06:51
I have also had the same problem since the update

**Comment by Vladx71** [comment] 2024-06-06 07:19
same here

**Comment by Steffen1964** [comment] 2024-06-06 07:23
sam here

**Comment by B4S71** [comment] 2024-06-06 07:36
[pyllant.log](https://github.com/user-attachments/files/15605347/pyllant.log)

`homeassistant.requirements.RequirementsNotFound: Requirements for mypyllant not found: ['myPyllant==0.8.9'].`
However, checking pypi, the package is available, installing it manually does work. 
Can't seem to understand what's happening exaclty.

**Comment by B4S71** [comment] 2024-06-06 07:49
> > [pyllant.log](https://github.com/user-attachments/files/15605347/pyllant.log)
> > `homeassistant.requirements.RequirementsNotFound: Requirements for mypyllant not found: ['myPyllant==0.8.9'].` However, checking pypi, the package is available, installing it manually does work. Can't seem to understand what's happening exaclty.
> 
> How can you install manually?
> 
> Thanks L:

I was just checking whether myPyllant==0.8.9 would install on another system (in that case the HASS-OS), which it does. It is not a workaround or something alike, just a check wheter the package is available, which it is.

**Comment by alexskynet** [comment] 2024-06-06 07:52
At a first look it seems py3-aioresponses 0.7.6 is not available (just  0.7.5) so this breaks installation

**Comment by Roadis** [comment] 2024-06-06 07:52
Beta Version with 0.8.11 also doesn't work

Logger: homeassistant.util.package
Quelle: util/package.py:123
Erstmals aufgetreten: 09:50:58 (3 Vorkommnisse)
Zuletzt protokolliert: 09:51:13

Unable to install package myPyllant==0.8.11: ERROR: Cannot install mypyllant==0.8.11 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by ecranbleu27** [comment] 2024-06-06 08:34
+1

**Comment by barto64** [comment] 2024-06-06 08:52
Same here too. I tried to change the componente dependency to the latest version of the API (0.8.11) but it did not work. As stated before there are internal dependencias missed than cannot be solved.

**Comment by corelanc0d3r** [comment] 2024-06-06 09:19
same here

**Comment by coreGreenberet** [comment] 2024-06-06 09:36
duplicate of #165

**Comment by MarcelNoir** [comment] 2024-06-06 09:47
+1 here

**Comment by joselaya** [comment] 2024-06-06 11:12
Fixed! Version v0.8.3 
Thx 👍🏽

**Comment by R1200G** [comment] 2024-06-06 11:13
Sorry but how can I update? 
I can’t find any option…

**Comment by joselaya** [comment] 2024-06-06 11:19
> Sorry but how can I update? I can’t find any option…

Go to HACS - myPyllant integration - Click on ‘redownload’

**Comment by PV-Joe** [comment] 2024-06-06 11:29
Thanks for the quick fix.
Its working again 👍

**Comment by R1200G** [comment] 2024-06-06 11:35
> > Sorry but how can I update? I can’t find any option…
> 
> Go to HACS - myPyllant integration - Click on ‘redownload’

Of course 🤦🏼‍♂️ Thank you very much! 😊

**Comment by Vladx71** [comment] 2024-06-06 12:54
> > > Sorry but how can I update? I can’t find any option…
> > 
> > 
> > Go to HACS - myPyllant integration - Click on ‘redownload’
> 
> Of course 🤦🏼‍♂️ Thank you very much! 😊

Confirmed. Fixed :) Thank you

**Comment by hzulla** [comment] 2024-06-07 14:38
Thank you very much!

**Comment by stricke2002** [comment] 2024-06-07 22:39
Hello, 

I have the same problem too. I tried to redownload but it still doesn’t work. I get the following two errors:
Logger: homeassistant.util.package
Source: util/package.py:123
First occurred: 00:33:01 (3 occurrences)
Last logged: 00:33:06
Unable to install package myPyllant==0.8.12: ERROR: Cannot install mypyllant==0.8.12 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:190
First occurred: 00:31:56 (2 occurrences)
Last logged: 00:31:58

    Detected that custom integration 'hacs' accesses hass.components.frontend. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from frontend directly at custom_components/hacs/frontend.py, line 68: hass.components.frontend.async_register_built_in_panel(, please create a bug report at https://github.com/hacs/integration/issues
    Detected that custom integration 'hacs' accesses hass.helpers.event. This is deprecated and will stop working in Home Assistant 2024.11, it should be updated to import functions used from event directly at custom_components/hacs/base.py, line 642: self.hass.helpers.event.async_track_time_interval(, please create a bug report at https://github.com/hacs/integration/issues

**Comment by ggonzalez** [comment] 2024-06-18 08:05
Same issue with HA 2.5.3

Unable to install package myPyllant==0.8.12: ERROR: Cannot install mypyllant==0.8.12 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by signalkraft** [comment] 2024-07-02 13:40
Should work in the latest release https://github.com/signalkraft/mypyllant-component/releases/tag/v0.8.4

**Closed by signalkraft** 2024-07-02 13:40 UTC
