### ISSUE TITLE
KeyError: 'system_water_pressure'

### ISSUE THREAD

**Issue by zarch1972** [signalkraft/mypyllant-component#7] opened 2023-03-27 09:04 UTC
Just migrated from sensoApp to myVaillant on my 5kW Arotherm Plus heat pump.
I get the following error on home assistant reboot.

This was a fresh install of the integration via HACS.

```
Logger: homeassistant.setup
Source: setup.py:320
First occurred: 09:50:29 (1 occurrences)
Last logged: 09:50:29

Unable to prepare setup for platform mypyllant.water_heater: Platform not found (cannot import name 'UnitOfTemperature' from 'homeassistant.components.water_heater' (/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py)).
```

```
today at 09:59 Traceback (most recent call last):
today at 09:59 File "/usr/local/lib/python3.10/site-packages/myPyllant/models.py", line 173, in water_pressure
today at 09:59 return self.system_control_state["control_state"]["general"][
today at 09:59 KeyError: 'system_water_pressure'
```

Water pressure entity showing 'unknown'

![image](https://user-images.githubusercontent.com/23335221/227892755-cfb99164-bb4b-4d90-b466-d259bd2f5564.png)

I have tested this on HA 2022.11.2 and 2023.3.6

**Comment by signalkraft** [comment] 2023-03-30 17:42
The first error should be fixed in the latest version, although I could not reproduce it.

The last error is only a info message, I've removed it from the latest release. Your system doesn't seem to report water pressure in the same way as mine, so the sensor goes to unknown. You could try turning on debug logging and looking through the logs for water pressure data: https://github.com/signalkraft/mypyllant-component#debugging

If you can find how your system reports this data, I may be able to add it.

**Comment by signalkraft** [comment] 2023-04-09 17:38
@zarch1972 did it work?

**Comment by zarch1972** [comment] 2023-04-10 12:13
Hi there

The major python error went away, but I still this error
`2023-04-10 13:10:30.422 INFO (MainThread) [myPyllant.models] Could not get water pressure from system control state`

I turned debug on and can see the following being pulled back into the long JSON collection.

`operational_data={'water_pressure': {'value': 1.1, 'unit': 'BAR', 'step_size': 0.1}},`

Hope this helps.

Thanks for checking this out.

**Comment by signalkraft** [comment] 2023-04-13 22:40
You may have better luck with the new release, I added a 2nd sensor for the water pressure data you are seeing.

**Comment by zarch1972** [comment] 2023-04-14 12:47
Thanks for the update, that has resolved it!

![image](https://user-images.githubusercontent.com/23335221/232047591-8e8446cd-d414-48e4-8df5-8e24675b71c2.png)

**Comment by signalkraft** [comment] 2023-04-14 16:57
Glad to hear that! Could you let me know the names of your Vaillant devices, so I can add you setup to the list of tested combinations?

**Comment by zarch1972** [comment] 2023-04-15 10:27
No problem, is that what you're after?

5kW Arotherm Plus Heat Pump (VWL 55/6 A)
Heatpump Interface (VWZ AI)
Sensonet (VR921)
Sensocomfort RF (VRC 720)

**Comment by signalkraft** [comment] 2023-04-16 10:31
Thanks!

**Closed by signalkraft** 2023-04-16 10:31 UTC
